loki:
  auth_enabled: true
  storage:
    type: s3
    bucketNames: 
      chunks: amg-loki-datastore
      ruler: amg-loki-datastore
      admin: amg-loki-datastore
    s3:
      endpoint: null
      region: ap-southeast-2
      #s3forcepathstyle: false
      sse_encryption: true
      insecure: false
      http_config:
        insecure_skip_verify: true
serviceAccount:
  create: false
  name: loki-s3
gateway:
  enabled: true
  service:
    type: NodePort
  ingress:
    enabled: true
    ingressClassName: "alb"
    annotations:
      alb.ingress.kubernetes.io/scheme  : internet-facing
      alb.ingress.kubernetes.io/ip-address-type  : ipv4
    hosts:
      - paths:
          - path: /
            pathType: Prefix
  basicAuth:
    enabled: true
    username: test
    password: test